name: Deploy ClojureScript SPA to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache Clojure dependencies
      - name: Cache Clojure Deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-clj-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clj-

      # Cache JS dependencies (Bun)
      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            bun.lockb
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.12.1.1550

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'  # or specify a version

      - name: Install dependencies
        run: bun install

      - name: Update dependencies
        run: bun update

      - name: Build ClojureScript
        run: clojure -M -m figwheel.main -bo dev

      - name: Prepare Deployment Files
        run: |
          mkdir -p docs
          cp -a resources/public/ docs/
          cp target/public/cljs-out/dev/main_bundle.js docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
